config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :categories
  resources :articles do
    resources :comments
  end
  devise_for :users
  resources:emp
  root to: 'pages#index'
  get 'pages/contact'
  get 'pages/custom_form'
  get 'pages/about'
  get 'pages/form'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
        belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/emp.rb
class Emp < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
    has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Emp was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:firstname, :lastname, :position, :salary, :admin, :dob)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(params[:comment].permit(:body))
        @comment.user_id = current_user.id if current_user
        if @comment.save
        redirect_to article_path(@article), notice: "Your comment has been saved."
        else
        redirect_to 'new'
        end
        end
    def update
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        if @comment.update(params[:comment].permit(:body))
        redirect_to article_path(@article), notice: "Your comment has been updated."
        else
        render 'edit'
        end
        end
    def edit
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
    end
    def destroy
            @article = Article.find(params[:article_id])
            @comment = @article.comments.find(params[:id])
            @comment.destroy
            redirect_to article_path(@article), notice: "Your comment has been deleted."
    end
    end

app/controllers/emp_controller.rb
class EmpController < ApplicationController
    def new
        @emp=emp.new
    end

    def create
        @emp=emp.new(params[:emp])
        if @emp.save
            redirect_to new_emp_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @articles = Article.last(5)
  end

  def contact
  end

  def about
  end

  def form
  end
end

app/controllers/ragistrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
def sign_up_params
params.require(:user).permit(
:email,
:password,
:password_confirmation,
:username,
:firstname,
:lastname
)
end
def account_update_params
params.require(:user).permit(
:email,
:password,
:password_confirmation,
:current_password,
:username,
:firstname,
:lastname
)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/emp_helper.rb
module EmpHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Articles</h1>
<table class="table table-striped">

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :position %>
    <%= f.input :salary %>
    <%= f.input :admin %>
    <%= f.input :dob %>
  </div>

  <div class="form-actions">
    <%= f.button :submit ,"Add new emp"%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee Records</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Position</th>
      <th>Salary</th>
      <th>Admin</th>
      <th>Dob</th>
      <th colspan="3"></th>
    </tr>
  </thead

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.firstname %></td>
        <td><%= category.lastname %></td>
        <td><%= category.position %></td>
        <td><%= category.salary %></td>
        <td><%= category.admin %></td>
        <td><%= category.dob %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= render 'comments/comment' %>
<br>
<%= link_to 'Add new emp.', new_category_path %>

app/views/categories/new.html.erb
<h1>New Employee</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @category.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @category.lastname %>
</p>

<p>
  <strong>Position:</strong>
  <%= @category.position %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @category.salary %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @category.admin %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @category.dob %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_comment.html.erb
<div class="media">
<div class="pull-left">
</div>
<div class="media-body">
<p class="media-heading pull-right">
Testing
</p>
</div>
</div>

app/views/comments/edit.html.erb
<h1> Edit Comment</h1>
<%= simple_form_for([@article, @comment]) do |f| %>
<%= f.input :body %>
<%= f.submit %>
<% end %>

app/views/layouts/_foot.html.erb
<footer class="footer-distributed navbar-fixed-bottom">
<div class="footer-right">
<a href="#"><i class="fa fa-facebook"></i></a>
<a href="#"><i class="fa fa-twitter"></i></a>
<a href="#"><i class="fa fa-linkedin"></i></a>
<a href="#"><i class="fa fa-github"></i></a>
</div>
<div class="footer-left">
<p class="footer-links">

<%= link_to "Contact Us", pages_contact_path, class: "page-scroll" %>

<%= link_to "About Us", pages_about_path, class: "page-scroll" %>

</p>
<p> </p>
</div>
<footer class="footer-distributed navbar-fixed-bottom">
<div class="footer-right">
<a href="#"><i class="fa fa-facebook"></i></a>
<a href="#"><i class="fa fa-twitter"></i></a>
<a href="#"><i class="fa fa-linkedin"></i></a>
<a href="#"><i class="fa fa-github"></i></a>
</div>
<div class="footer-left">
<p class="footer-links">

<%= link_to "Contact Us", pages_contact_path, class: "page-scroll" %>

<%= link_to "About Us", pages_about_path, class: "page-scroll" %>

</p>
<p> </p>
</div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-
example-navbar-collapse-1" aria-expanded="false">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<%= link_to "Komal's Articles", root_path, class: 'navbar-brand' %>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav navbar-right">
<li><%= link_to "Contact Us", pages_contact_path %></li>
<li><%= link_to "About us", pages_about_path %></li>
<li><%= link_to "Create an Article", new_article_path %></li>
<% if !current_user %>
<li><%= link_to "Sign Up", new_user_registration_path %></li>
<li><%= link_to "Sign in", new_user_session_path %></li>

<% else %>
<li class="dropdown">


<ul class="dropdown-menu">
<li><a href="#">Action</a></li>
<li><a href="#">Another action</a></li>
<li><%= link_to "Edit My Profile", edit_user_registration_path %></li>
<li role="separator" class="divider"></li>
<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
</ul>
</li>
</ul>

<% end %>

</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Komal s Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= bootstrap_flash %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render'layouts/nav'%>
<div class="container">
    <%= yield %>
    </div>
    <%= render 'layouts/foot' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row">
<div class="col-lg-12 text-center">
<h1>About Us</h1>
<p class="lead">Test Text</p>
<ul class="list-unstyled">
<li>List Item</li>
<li>List Item 2</li>
</ul>
</div>
</div>

app/views/pages/contact.html.erb
<div class="row">
<div class="col-lg-12 text-center">
<h1>Contact Us</h1>
<p class="lead">Test Text</p>
<ul class="list-unstyled">
<li>List Item</li>
<li>List Item 2</li>
</ul>
</div>
</div>

app/views/pages/custom_form.html.erb
<h2>Employee Reg. Form</h2>

<%= simple_form_for(@emp) do |f| %>
  <div class="form-inputs">
      <%= f.input :email%>
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    
    <%= f.input :password %>
   
  </div>


    <%= f.submit %>
  
<% end %>

app/views/pages/form.html.erb
<h1>Pages#form</h1>
<p>Find me in app/views/pages/form.html.erb</p>

app/views/pages/index.html.erb
<!--Index Page-->
<div class="row">
<!-- Blog Post Content Column -->
<div class="col-lg-8">
<!-- Blog Post -->
<!-- Title -->
<h1>Blog Post Title</h1>
<!-- Author -->
<p class="lead">
by <a href="#">Start Bootstrap</a>
</p>
<hr>
<!-- Date/Time -->
<p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>
<hr>
<!-- Preview Image -->
<img class="img-responsive" src="http://placehold.it/900x300" alt="">
<hr>
<!-- Post Content -->
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero,
obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi
eos magni recusandae laborum minus inventore?</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum
quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat.
Temporibus, voluptatibus.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto
blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat
perspiciatis. Enim, iure!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas
placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem
obcaecati?</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo,
aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam
recusandae? Qui, necessitatibus, est!</p>
<hr>
<!-- Blog Comments -->
<!-- Comments Form -->
<div class="well">
<h4>Leave a Comment:</h4>
<form role="form">
<div class="form-group">
<textarea class="form-control" rows="3"></textarea>
</div>
<button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
<hr>
<!-- Posted Comments -->
<!-- Comment -->
<div class="media">
<a class="pull-left" href="#">
<img class="media-object" src="http://placehold.it/64x64" alt="">
</a>
<div class="media-body">
<h4 class="media-heading">Start Bootstrap
<small>August 25, 2014 at 9:30 PM</small>
</h4>
Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
</div>
</div>
<!-- Comment -->
<div class="media">
<a class="pull-left" href="#">
<img class="media-object" src="http://placehold.it/64x64" alt="">
</a>
<div class="media-body">
<h4 class="media-heading">Start Bootstrap
<small>August 25, 2014 at 9:30 PM</small>
</h4>
Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
<!-- Nested Comment -->
<div class="media">
<a class="pull-left" href="#">
<img class="media-object" src="http://placehold.it/64x64" alt="">
</a>
<div class="media-body">
<h4 class="media-heading">Nested Start Bootstrap
<small>August 25, 2014 at 9:30 PM</small>
</h4>
Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
</div>
</div>
<!-- End Nested Comment -->
</div>
</div>
</div>
<!-- Blog Sidebar Widgets Column -->
<div class="col-md-4">


<!-- Side Widget Well -->
<div class="well">
<h4>Recent Posts</h4>
<% @articles.each do |a| %>
<%= a.title %>
<%= a.body %>
<% end %>


<h4>Blog Search</h4>
<div class="input-group">
<input type="text" class="form-control">
<span class="input-group-btn">
<button class="btn btn-default" type="button">
<span class="glyphicon glyphicon-search"></span>
</button>
</span>
</div>
<!-- /.input-group -->
</div>
<!-- Blog Categories Well -->
<div class="well">
<h4>Blog Categories</h4>
<div class="row">
<div class="col-lg-6">
<ul class="list-unstyled">
<li><a href="#">Category Name</a>
</li>
<li><a href="#">Category Name</a>
</li>
<li><a href="#">Category Name</a>
</li>
<li><a href="#">Category Name</a>
</li>
</ul>
</div>
<div class="col-lg-6">
<ul class="list-unstyled">
<li><a href="#">Category Name</a>
</li>
<li><a href="#">Category Name</a>
</li>
<li><a href="#">Category Name</a>
</li>
<li><a href="#">Category Name</a>
</li>
</ul>
</div>
</div>
<!-- /.row -->
</div>
<div class="well">
<h4>Side Widget Well</h4>
<div class="well">
<h4>Recent Posts</h4>
<% @articles.each do |a| %>
<strong><%= link_to a.title, a %></strong>
<p><%= truncate(a.body) %></p>
<% end %>
</div>
</div>
</div>
<!-- /.row -->
<hr>